version: '3.1'
services :
  db:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./tablespace.sh:/docker-entrypoint-initdb.d/tablespace.sh
    ports:
      - "5432:5432"
  admin:
    image: adminer
    depends_on: 
      - db
    ports:
      - 8080:8080


