HEPAddr               = "0.0.0.0:9060"
HEPTCPAddr            = "0.0.0.0:9060"
HEPTLSAddr            = ""
HEPWSAddr             = ""
ESAddr                = ""
ESDiscovery           = true
LokiURL               = ""
LokiBulk              = 200
LokiTimer             = 4
LokiBuffer            = 100000
LokiHEPFilter         = [1,5,100]
ForceHEPPayload	      = []
PromAddr              = ""
PromTargetIP          = ""
PromTargetName        = ""
DBShema               = "homer7"
DBDriver              = "postgres"
DBDataTable           = "homer_data"
DBDataAddr            = "127.0.0.1:5432"
DBDataUser            = "homer"
DBDataPass            = "123456"
DBConfTable           = "homer_config"
DBConfAddr            = "127.0.0.1:5432"
DBConfUser            = "homer"
DBConfPass            = "123456"
DBBulk                = 200
DBTimer               = 4
DBBuffer              = 400000
DBWorker              = 8
DBRotate              = true
DBPartLog             = "2h"
DBPartSip             = "1h"
DBPartQos             = "6h"
DBDropDays            = 7
DBDropDaysCall        = 7
DBDropDaysRegister    = 7
DBDropDaysDefault     = 7
DBProcDropLimit       = 24
DBDropOnStart         = true
DBUsageProtection     = true
DBUsageScheme         = "percentage"
DBPercentageUsage     = "90%"
#DBMaxSize             = "30MB"
Dedup                 = false
DiscardMethod         = []
AlegIDs               = []
CustomHeader          = ["X-CID","token"]
SIPHeader             = ["callid","cseq","method","from_user","to_user","from_tag","ruri_user","ruri_domain","user_agent","via_branch"]
LogDbg                = ""
LogLvl                = "info"
LogStd                = true
Config                = "./heplify-server.toml"
ConfigHTTPAddr        = ""

# Examples:
# -------------------------------------
# ESAddr          = "http://127.0.0.1:9200"
# DBShema         = "homer7"
# DBDriver        = "postgres"
# LokiURL         = "http://localhost:3100/api/prom/push"
# LokiHEPFilter   = [1,5,100]
# PromAddr        = "0.0.0.0:8899"
# PromTargetIP    = "10.1.2.111,10.1.2.4,10.1.2.5,10.1.2.6,10.12.44.222"
# PromTargetName  = "sbc_access,sbc_core,kamailio,asterisk,pstn_gateway"
# AlegIDs         = ["X-CID","P-Charging-Vector,icid-value=\"?(.*?)(?:\"|;|$)","X-BroadWorks-Correlation-Info"]
# DiscardMethod   = ["OPTIONS","NOTIFY"]
# CustomHeader    = ["X-CustomerIP","X-Billing"]
# SIPHeader       = ["callid","callid_aleg","method","ruri_user","ruri_domain","from_user","from_domain","from_tag","to_user","to_domain","to_tag","via","contact_user"]
# LogDbg          = "hep,sql,loki"
# LogLvl          = "warning"
# ConfigHTTPAddr  = "0.0.0.0:9876"
# -------------------------------------
# To hot reload PromTargetIP and PromTargetName run:
# killall -HUP heplify-server
