version: '3.1'
services :
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
  admin:
    image: adminer
    depends_on: 
      - db
    ports:
      - 8080:8080

