project_name: homer-app
release:
  github:
    owner: sipcapture
    name: homer-app
  name_template: '{{.Tag}}'
brews:
- name: homer-app
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  goarm: "6"
scoop:
  name: homer-app
  commit_author:
    name: sipcapture_release
    email: alexandr.dubovikov@gmail.com
builds:
- id: homer-app
  goos:
  - linux
  goarch:
  - amd64
  goarm:
  - "6"
  targets:
  - linux_amd64
  dir: .
  main: .
  ldflags:
  - -s -w
  binary: homer-app
  env:
  - CGO_ENABLED=0
  lang: go
archives:
- id: default
  builds:
  - homer-app
  name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm
    }}v{{ .Arm }}{{ end }}'
  replacements:
    "386": i386
    amd64: x86_64
    darwin: Darwin
    linux: Linux
    windows: Windows
  format: tar.gz
  files:
  - licence*
  - LICENCE*
  - license*
  - LICENSE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*
snapshot:
  name_template: '{{ .Tag }}-next'
checksum:
  name_template: checksums.txt
  algorithm: sha256
changelog:
  filters:
    exclude:
    - '^docs:'
    - '^test:'
  sort: asc
dist: release
signs:
- cmd: gpg
  args:
  - --output
  - $signature
  - --detach-sig
  - $artifact
  signature: ${artifact}.sig
  artifacts: none
env_files:
  github_token: ~/.config/goreleaser/github_token
  gitlab_token: ~/.config/goreleaser/gitlab_token
  gitea_token: ~/.config/goreleaser/gitea_token
before:
  hooks:
  - go mod tidy
  - go generate ./...
github_urls:
  download: https://github.com
gitlab_urls:
  download: https://gitlab.com
